# Generated by Django 3.0.5 on 2020-06-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='clothestype',
            options={'ordering': ['name'], 'verbose_name': 'Тип одежды', 'verbose_name_plural': 'Типы одежды'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['new', 'name'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['done', 'date'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['viewed', 'date'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.ImageField(default=1, upload_to='main/item/photo', verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
