# Generated by Django 3.0.5 on 2020-06-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
