# Generated by Django 3.0.5 on 2020-06-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200602_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-new', 'name'], 'verbose_name': 'Вещь', 'verbose_name_plural': 'Вещи'},
        ),
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.FloatField(verbose_name='Цена, руб.'),
        ),
        migrations.AlterField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=False, verbose_name='Новое'),
        ),
    ]
