# Generated by Django 3.0.5 on 2020-06-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200602_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
