# Generated by Django 3.0.5 on 2020-06-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200602_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost_fractional',
            field=models.IntegerField(default=0, verbose_name='Цена, коп.'),
        ),
    ]
