# Generated by Django 3.0.5 on 2020-06-04 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0010_cartpiece'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('done', models.BooleanField(default=False, verbose_name='Выполнен')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='main.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_piece', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупка заказанная',
                'verbose_name_plural': 'Покупки заказанные',
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
